version: "3"

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile

        volumes:
            - ./:/app

        working_dir: "/app"

        ports:
            - 8080:8080

        command: [
            "lona", "run-server",
                "--project-root", "lona_project",
                "--settings", "settings.py",
                "--host", "0.0.0.0",
                "--port", "8080",
                "--log-level", "info",
        ]
